export const TASK_LOAD_REQUEST = "TASK_LOAD_REQUEST";
export const TASK_LOAD_SUCCESS = "TASK_LOAD_SUCCESS";
export const TASK_LOAD_FAIL = "TASK_LOAD_FAIL";
export const TASK_LOAD_RESET = "TASK_LOAD_RESET";

export const TASK_SINGLE_REQUEST = "TASK_SINGLE_REQUEST";
export const TASK_SINGLE_SUCCESS = "TASK_SINGLE_SUCCESS";
export const TASK_SINGLE_FAIL = "TASK_SINGLE_FAIL";
export const TASK_SINGLE_RESET = "TASK_SINGLE_RESET";

export const TASK_SINGLE_EDIT_REQUEST = "TASK_SINGLE_EDIT_REQUEST";
export const TASK_SINGLE_EDIT_SUCCESS = "TASK_SINGLE_EDIT_SUCCESS";
export const TASK_SINGLE_EDIT_FAIL = "TASK_SINGLE_EDIT_FAIL";
export const TASK_SINGLE_EDIT_RESET = "TASK_SINGLE_EDIT_RESET";
